vlib $env(SOC_IT_SIMULATION_PATH)/brute_force_matcher
vmap brute_force_matcher $env(SOC_IT_SIMULATION_PATH)/brute_force_matcher


#vlog -lint -sv +define+simulation +define+SIMULATION -work brute_force_matcher +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog_2 $env(SOC_IT_ROOT)/brute_force_matcher/hardware/ip/xcku115/brute_force_matcher_squareRoot/brute_force_matcher_squareRoot_sim_netlist.v
#vlog -lint -sv +define+simulation +define+SIMULATION -work brute_force_matcher +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog_2 $env(SOC_IT_ROOT)/brute_force_matcher/hardware/ip/xcku115/brute_force_matcher_fixed_to_flt/brute_force_matcher_fixed_to_flt_sim_netlist.v
#vlog -lint -sv +define+simulation +define+SIMULATION -work brute_force_matcher +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog_2 $env(SOC_IT_ROOT)/brute_force_matcher/hardware/ip/xcku115/brute_force_matcher_dispatch_unit_dwc_fifo/brute_force_matcher_dispatch_unit_dwc_fifo_sim_netlist.v
#vlog -lint -sv +define+simulation +define+SIMULATION -work brute_force_matcher +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog_2 $env(SOC_IT_ROOT)/brute_force_matcher/hardware/ip/xcku115/brute_force_matcher_dispatch_unit_dwc_fifo_64dsp/brute_force_matcher_dispatch_unit_dwc_fifo_64dsp_sim_netlist.v
#vlog -lint -sv +define+simulation +define+SIMULATION -work brute_force_matcher +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog_2 $env(SOC_IT_ROOT)/brute_force_matcher/hardware/ip/xcku115/brute_force_matcher_secondary_buffer_fifo_64dsp0/brute_force_matcher_secondary_buffer_fifo_64dsp0_sim_netlist.v
#vlog -lint -sv +define+simulation +define+SIMULATION -work brute_force_matcher +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog_2 $env(SOC_IT_ROOT)/brute_force_matcher/hardware/ip/xcku115/brute_force_matcher_secondary_buffer_fifo_64dsp1/brute_force_matcher_secondary_buffer_fifo_64dsp1_sim_netlist.v
#vlog -lint -sv +define+simulation +define+SIMULATION -work brute_force_matcher +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog_2 $env(SOC_IT_ROOT)/brute_force_matcher/hardware/ip/xcku115/brute_force_matcher_secondary_buffer_fifo/brute_force_matcher_secondary_buffer_fifo_sim_netlist.v
#vlog -lint -sv +define+simulation +define+SIMULATION -work brute_force_matcher +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog_2 $env(SOC_IT_ROOT)/brute_force_matcher/hardware/ip/xcku115/brute_force_matcher_match_table_info_bram/brute_force_matcher_match_table_info_bram_sim_netlist.v
#vlog -lint -sv +define+simulation +define+SIMULATION -work brute_force_matcher +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog_2 $env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog_2/brute_force_matcher_dispatch_unit.v		
#vlog -lint -sv +define+simulation +define+SIMULATION -work brute_force_matcher +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog_2 $env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog_2/brute_force_matcher_match_table.v
#vlog -lint -sv +define+simulation +define+SIMULATION -work brute_force_matcher +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog_2 $env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog_2/brute_force_matcher_format_conv.v
#vlog -lint -sv +define+simulation +define+SIMULATION -work brute_force_matcher +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog_2 $env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog_2/brute_force_matcher_preSubSquareAccum_DSP.v
#vlog -lint -sv +define+simulation +define+SIMULATION -work brute_force_matcher +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog_2 $env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog_2/brute_force_matcher_circular_descriptor_buffer.v
#vlog -lint -sv +define+simulation +define+SIMULATION -work brute_force_matcher +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog_2 $env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog_2/brute_force_matcher_secondary_descriptor_buffer.v
#vlog -lint -sv +define+simulation +define+SIMULATION -work brute_force_matcher +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog_2 $env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog_2/SRL_bit.v
#vlog -lint -sv +define+simulation +define+SIMULATION -work brute_force_matcher +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog_2 $env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog_2/SRL_bus.v
#vlog -lint -sv +define+simulation +define+SIMULATION -work brute_force_matcher +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog_2 $env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog_2/address_incrementer.v
#vlog -lint -sv +define+simulation +define+SIMULATION -work brute_force_matcher +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog_2 $env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog_2/brute_force_matcher.v
#vlog -lint -sv +define+simulation +define+SIMULATION -work brute_force_matcher +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog_2 $env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog_2/brute_force_matcher_controller.v
#vlog -lint -sv +define+simulation +define+SIMULATION -work brute_force_matcher +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog_2 $env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog_2/brute_force_matcher_descriptor_compute_pipeline.v
#vlog -lint -sv +define+simulation +define+SIMULATION -work brute_force_matcher +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog_2 $env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog_2/brute_force_matcher_keyPointEngine.v
#vlog -lint -sv +define+simulation +define+SIMULATION -work brute_force_matcher +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog_2 $env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog_2/brute_force_matcher_secondary_buffer_control.v
#vlog -lint -sv +define+simulation +define+SIMULATION -work brute_force_matcher +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog_2 $env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog_2/master_transactor.v
#vlog -lint -sv +define+simulation +define+SIMULATION -work brute_force_matcher +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog_2 $env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog_2/brute_force_matcher_engine.v
#vlog -lint -sv +define+simulation +define+SIMULATION -work brute_force_matcher +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog_2 $env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog_2/master_if_arbiter_nway.v
#vlog -lint -sv +define+simulation +define+SIMULATION -work brute_force_matcher +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog_2 $env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog_2/xilinx_simple_dual_port_1_clock_ram.v
#vlog -lint -sv +define+simulation +define+SIMULATION -work brute_force_matcher +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog_2 $env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog_2/brute_force_matcher_datapath.v
#vlog -lint -sv +define+simulation +define+SIMULATION -work brute_force_matcher +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog_2_4 $env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog_2/xilinx_simple_dual_port_2_clock_ram.v


vlog -work brute_force_matcher $env(SOC_IT_ROOT)/brute_force_matcher/hardware/ip/xcku115/brute_force_matcher_secondary_buffer_fifo_64dsp0/sim/brute_force_matcher_secondary_buffer_fifo_64dsp0.v
vlog -work brute_force_matcher $env(SOC_IT_ROOT)/brute_force_matcher/hardware/ip/xcku115/brute_force_matcher_secondary_buffer_fifo_64dsp1/sim/brute_force_matcher_secondary_buffer_fifo_64dsp1.v
vlog -work brute_force_matcher $env(SOC_IT_ROOT)/brute_force_matcher/hardware/ip/xcku115/brute_force_matcher_secondary_buffer_fifo/sim/brute_force_matcher_secondary_buffer_fifo.v
vlog -work brute_force_matcher $env(SOC_IT_ROOT)/brute_force_matcher/hardware/ip/xcku115/brute_force_matcher_match_table_info_bram/sim/brute_force_matcher_match_table_info_bram.v
vlog -work brute_force_matcher $env(SOC_IT_ROOT)/brute_force_matcher/hardware/ip/xcku115/fifo_74_74_1024_fwft/sim/fifo_74_74_1024_fwft.v
vlog -work brute_force_matcher $env(SOC_IT_ROOT)/brute_force_matcher/hardware/ip/xcku115/brute_force_matcher_squareRoot/brute_force_matcher_squareRoot_sim_netlist.v
vlog -work brute_force_matcher $env(SOC_IT_ROOT)/brute_force_matcher/hardware/ip/xcku115/brute_force_matcher_fixed_to_flt/brute_force_matcher_fixed_to_flt_sim_netlist.v
#vcom -work brute_force_matcher C:/SOC_IT/brute_force_matcher/hardware/ip/xcku115/brute_force_matcher_fixed_to_flt/sim/brute_force_matcher_fixed_to_flt.vhd
#vcom -work brute_force_matcher C:/SOC_IT/brute_force_matcher/hardware/ip/xcku115/brute_force_matcher_squareRoot/sim/brute_force_matcher_squareRoot.vhd
vlog -lint -sv +define+simulation +define+SIMULATION -work brute_force_matcher +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog $env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog/brute_force_matcher_dispatch_unit.v
vlog -lint -sv +define+simulation +define+SIMULATION -work brute_force_matcher +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog $env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog/brute_force_matcher_match_table.v
vlog -lint -sv +define+simulation +define+SIMULATION -work brute_force_matcher +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog $env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog/brute_force_matcher_circular_descriptor_buffer.v
vlog -lint -sv +define+simulation +define+SIMULATION -work brute_force_matcher +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog $env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog/brute_force_matcher_secondary_descriptor_buffer.v
vlog -lint -sv +define+simulation +define+SIMULATION -work brute_force_matcher +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog $env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog/address_incrementer.v
vlog -lint -sv +define+simulation +define+SIMULATION -work brute_force_matcher +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog $env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog/brute_force_matcher.v
vlog -lint -sv +define+simulation +define+SIMULATION -work brute_force_matcher +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog $env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog/brute_force_matcher_controller.v
vlog -lint -sv +define+simulation +define+SIMULATION -work brute_force_matcher +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog $env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog/brute_force_matcher_descriptor_compute_pipeline.v
vlog -lint -sv +define+simulation +define+SIMULATION -work brute_force_matcher +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog $env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog/brute_force_matcher_secondary_buffer_control.v
vlog -lint -sv +define+simulation +define+SIMULATION -work brute_force_matcher +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog $env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog/master_transactor.v
vlog -lint -sv +define+simulation +define+SIMULATION -work brute_force_matcher +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog $env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog/brute_force_matcher_engine.v
vlog -lint -sv +define+simulation +define+SIMULATION -work brute_force_matcher +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog $env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog/master_if_arbiter_nway.v
vlog -lint -sv +define+simulation +define+SIMULATION -work brute_force_matcher +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog $env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog/brute_force_matcher_datapath.v
vlog -lint -sv +define+simulation +define+SIMULATION -work brute_force_matcher +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog $env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog/brute_force_matcher_format_conv.v
vlog -lint -sv +define+simulation +define+SIMULATION -work brute_force_matcher +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog $env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog/xilinx_simple_dual_port_1_clock_ram.v
vlog -lint -sv +define+simulation +define+SIMULATION -work brute_force_matcher +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog $env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog/SRL_bit.v
vlog -lint -sv +define+simulation +define+SIMULATION -work brute_force_matcher +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog $env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog/SRL_bus.v
vlog -lint -sv +define+simulation +define+SIMULATION -work brute_force_matcher +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog $env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog/brute_force_matcher_keyPointEngine.v
vlog -lint -sv +define+simulation +define+SIMULATION -work brute_force_matcher +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog $env(SOC_IT_ROOT)/brute_force_matcher/hardware/verilog/brute_force_matcher_preSubSquareAccum_DSP.v
