# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mdl/izo5011/SOC_IT/brute_force_matcher/hardware/ip/xcku115/ila_300_4096/ila_300_4096.xci
# IP: The module: 'ila_300_4096' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mdl/izo5011/SOC_IT/brute_force_matcher/hardware/ip/xcku115/ila_300_4096/ila_v6_1/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_300_4096'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/mdl/izo5011/SOC_IT/brute_force_matcher/hardware/ip/xcku115/ila_300_4096/ila_300_4096_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_300_4096'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/mdl/izo5011/SOC_IT/brute_force_matcher/hardware/ip/xcku115/ila_300_4096/ila_300_4096.xci
# IP: The module: 'ila_300_4096' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mdl/izo5011/SOC_IT/brute_force_matcher/hardware/ip/xcku115/ila_300_4096/ila_v6_1/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_300_4096'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/mdl/izo5011/SOC_IT/brute_force_matcher/hardware/ip/xcku115/ila_300_4096/ila_300_4096_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_300_4096'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
